default_platform(:ios)

platform :ios do
  lane :dev do

    setup_ci

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY"],
      is_key_content_base64: true
    )

    match(
      type: "appstore",
      api_key: api_key,
      app_identifier: "com.cii.reno"
    )

    cocoapods(
      clean_install: true
    )

    increment_build_number(
      build_number: ENV["GITHUB_RUN_NUMBER"]
    )

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      configuration: "Release",
    )


    upload_to_testflight(
      api_key: api_key,
      groups: ["DEV"],
      distribute_external: false,
      skip_waiting_for_build_processing: true,
      uses_non_exempt_encryption: false
    )
  end
end
